#!/usr/bin/env sh

OLD_PWD="$PWD"
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
ROOT_DIR="${SCRIPT_DIR%scripts/make}"
DOC_DIR="$ROOT_DIR/docs"

cd "$ROOT_DIR" && (
    # Hides rm errors when some directories aren't found
    exec 2>/dev/null
    # Remove cache, installation and virtual environment directories
    find . -name "__pycache__" -type d -print0 | xargs -0 rm -r --
    rm -r -- .eggs *.egg-info build dist .venv .pytest_cache
    exec 2>/dev/tty
)

cd "$DOC_DIR" && make clean

cd "$OLD_PWD" || exit 1
