#!/usr/bin/env sh

OLD_PWD="$PWD"
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
DOC_DIR="${SCRIPT_DIR%scripts/make}/docs"

err() {
    cd "$OLD_PWD"
    exit 1
}

cd "$DOC_DIR" || exit 1

rm -r api _build
sphinx-apidoc -fMe ../pq -o api || err
echo "*** Generating HTML documentation ***"
make html || err
echo "*** Generating PDF documentation ***"
make latexpdf

cd "$OLD_PWD"
