#!/usr/bin/env sh

err() {
    cd "$OLD_PWD"
    exit 1
}

trap 'err' INT

OLD_PWD="$PWD"
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
ROOT_DIR=${SCRIPT_DIR%scripts/make}
VENV_DIR=".venv"

OS="$(lsb_release -si)"

if [ "$OS" = "Arch" ]; then
    (sudo pacman -Syu --needed python-pip qt5-base python-sphinx python-sphinx_rtd_theme) || err
elif [ "$OS" = "Ubuntu" ]; then
    (sudo apt -qq update && sudo apt -qq install python3-pip python3-venv sphinx-common sphinx-rtd-theme-common) || err
else
    echo "Unsupported OS: $OS. Will continue without installing system dependencies."
fi

cd "$ROOT_DIR" || err
echo "*** Creating virtual environment ***"
python3 -m venv "$VENV_DIR" || err
. "$VENV_DIR"/bin/activate || err
pip install -e . || err
deactivate || err

cd "$OLD_PWD"
echo "*** Done ***"
