#!/usr/bin/env sh

OLD_PWD="$PWD"
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
ROOT_DIR=${SCRIPT_DIR%scripts/make}
TEST_DIR="tests"
VENV_DIR=".venv"

err() {
    cd "$OLD_PWD"
    exit 1
}

cd "$ROOT_DIR" || exit 1

. "$VENV_DIR"/bin/activate || err

OS="$(lsb_release -si)"
if [ "$OS" = "Arch" ]; then
    # Allows running './TEST unit' to only run unit tests
    pytest "$TEST_DIR/$1"
elif [ "$OS" = "Ubuntu" ]; then
    pytest-3 "$TEST_DIR/$1"
fi

deactivate || err
cd "$OLD_PWD"
